"""add proposals, proposal_versions, estimations tables

Revision ID: 2ec7e869d5db
Revises: ce9bbf3dfb93
Create Date: 2026-07-06 12:56:21.402969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec7e869d5db'
down_revision = 'ce9bbf3dfb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'version_number')
    )
    op.create_table('estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_version_id', sa.Integer(), nullable=False),
    sa.Column('pricing_model', sa.Enum('FIXED', 'TIME_BASED', name='pricingmodel', native_enum=False, length=20), nullable=False),
    sa.Column('fixed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_unit', sa.Enum('HOURLY', 'DAILY', name='rateunit', native_enum=False, length=20), nullable=True),
    sa.Column('estimated_units', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('additional_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['proposal_version_id'], ['proposal_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimations')
    op.drop_table('proposal_versions')
    op.drop_table('proposals')
    # ### end Alembic commands ###
