"""add leads table

Revision ID: ce9bbf3dfb93
Revises: 7d79394739ed
Create Date: 2026-07-06 12:24:42.955157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9bbf3dfb93'
down_revision = '7d79394739ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PROPOSAL', 'OFFER_SENT', 'WON', 'LOST', name='leadstatus', native_enum=False, length=20), server_default='OPEN', nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('timeline', sa.String(length=255), nullable=True),
    sa.Column('budget_range', sa.String(length=255), nullable=True),
    sa.Column('discovery_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
