"""add offers, customers, projects tables

Revision ID: da8b5d4e5385
Revises: 2ec7e869d5db
Create Date: 2026-07-06 13:42:15.579195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8b5d4e5385'
down_revision = '2ec7e869d5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INTERNAL', 'EXTERNAL', name='customertype', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'DENIED', name='offerstatus', native_enum=False, length=20), server_default='DRAFT', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_version_id'], ['proposal_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('budget_type', sa.Enum('HARD', 'SOFT', name='budgettype', native_enum=False, length=20), nullable=False),
    sa.Column('budget_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('over_hours_policy', sa.Enum('BLOCK', 'BILL_AT_RATE', name='overhourspolicy', native_enum=False, length=20), nullable=True),
    sa.Column('over_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), server_default='ACTIVE', nullable=False),
    sa.CheckConstraint("budget_type != 'HARD' OR (budget_hours IS NOT NULL AND over_hours_policy IS NOT NULL)", name='ck_projects_hard_budget_fields'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('offers')
    op.drop_table('customers')
    # ### end Alembic commands ###
